# Generated by Django 5.0.4 on 2024-04-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hndik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=250, verbose_name='Site name')),
                ('name', models.CharField(max_length=250, verbose_name='Hndik name')),
                ('img', models.ImageField(upload_to='hndik/', verbose_name='Hndik image')),
                ('text', models.TextField(verbose_name='Hndik text')),
                ('but_name', models.CharField(max_length=250, verbose_name='Button name ')),
            ],
        ),
    ]
