# Generated by Django 5.0.4 on 2024-04-17 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hndik',
            name='site_name',
        ),
    ]
