# Generated by Django 5.0.4 on 2024-04-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_hndik_site_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='All prod name')),
                ('img', models.ImageField(upload_to='product/', verbose_name='Product image')),
                ('prod_name', models.CharField(max_length=250, verbose_name='Prod name')),
                ('new', models.BooleanField(verbose_name='Active')),
                ('price', models.BigIntegerField(verbose_name='Prod price')),
            ],
        ),
    ]
