# Generated by Django 5.0.4 on 2024-04-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_about_delete_index_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='offer/', verbose_name='Offer image')),
                ('name', models.BigIntegerField(verbose_name='Upto')),
                ('but_name', models.CharField(max_length=250, verbose_name='Button name')),
            ],
        ),
    ]
