# Generated by Django 5.0.4 on 2024-04-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Upto'),
        ),
    ]
