# Generated by Django 5.0.4 on 2024-04-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_offer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='blog/', verbose_name='Blog image')),
                ('name', models.CharField(max_length=250, verbose_name='Date')),
                ('title', models.CharField(max_length=250, verbose_name='Blog title')),
                ('text', models.TextField(verbose_name='Blog text')),
            ],
        ),
    ]
