# Generated by Django 5.0.4 on 2024-04-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_client_slider_delete_hndik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Mounth'),
        ),
    ]
