# Generated by Django 5.0.4 on 2024-04-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_blog_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='name1',
            field=models.CharField(default='SOME STRING', max_length=250, verbose_name='Date'),
        ),
    ]
